import { useEffect, useState, useRef } from 'react';
import {
  Siren, Shield, HeartPulse, Flame, CloudRain, MapPin, Phone,
  CheckCircle2, X, AlertTriangle, Mic, MicOff, Volume2, VolumeX,
  Radio, Sparkles, Navigation, LocateFixed, Activity, LifeBuoy, AlertOctagon
} from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/lib/auth';
import { Screen, ScreenHeader } from '@/components/Screen';
import { Button } from '@/components/Button';
import { Modal } from '@/components/Modal';
import { timeAgo } from '@/lib/utils';
import type { EmergencyRequest, EmergencyType } from '@/lib/types';

const types: { value: EmergencyType; label: string; icon: typeof Siren; color: string; bg: string; phone: string; desc: string }[] = [
  { value: 'police', label: 'Police 100', icon: Shield, color: 'text-secondary-600', bg: 'bg-secondary-600', phone: '100', desc: 'Crimes, break-ins, physical threats' },
  { value: 'ambulance', label: 'Ambulance 108', icon: HeartPulse, color: 'text-error-500', bg: 'bg-error-500', phone: '108', desc: 'Cardiac, trauma, breathlessness' },
  { value: 'fire', label: 'Fire 101', icon: Flame, color: 'text-accent-500', bg: 'bg-accent-500', phone: '101', desc: 'Building fire, LPG gas leak, sparks' },
  { value: 'disaster', label: 'Disaster 1077', icon: CloudRain, color: 'text-primary-600', bg: 'bg-primary-600', phone: '1077', desc: 'Flooding, storm, structural collapse' },
];

const getDistance = (lat1: number, lon1: number, lat2: number, lon2: number) => {
  const R = 6371; // Earth's radius in km
  const dLat = (lat2 - lat1) * Math.PI / 180;
  const dLon = (lon2 - lon1) * Math.PI / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) *
    Math.sin(dLon / 2) * Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return R * c;
};

// Protocol instructions generated by AI triage
interface AIProtocolStep {
  title: string;
  detail: string;
  important?: boolean;
}

export function Emergency({ onBack }: { onBack: () => void }) {
  const { session } = useAuth();
  const [requests, setRequests] = useState<EmergencyRequest[]>([]);
  const [loading, setLoading] = useState(true);
  const [confirmType, setConfirmType] = useState<EmergencyType | null>(null);
  const [active, setActive] = useState<EmergencyRequest | null>(null);
  const [countdown, setCountdown] = useState(3);

  // Live Sensor & Geolocation
  const [currentLat, setCurrentLat] = useState<number>(20.2961);
  const [currentLng, setCurrentLng] = useState<number>(85.8245);
  const [gpsAccuracy, setGpsAccuracy] = useState<number>(5);
  const [trackingGps, setTrackingGps] = useState(false);

  // AI Voice & Speech Recognition
  const [isListening, setIsListening] = useState(false);
  const [speechTranscript, setSpeechTranscript] = useState('');
  const recognitionRef = useRef<any>(null);

  // Audio Siren & Strobe Alarm
  const [sirenPlaying, setSirenPlaying] = useState(false);
  const audioCtxRef = useRef<AudioContext | null>(null);
  const oscRef = useRef<OscillatorNode | null>(null);

  // AI Triage Guidance
  const [triageSeverity, setTriageSeverity] = useState<'CRITICAL_L1' | 'HIGH_L2' | 'MODERATE_L3'>('HIGH_L2');
  const [protocolSteps, setProtocolSteps] = useState<AIProtocolStep[]>([]);

  // Operator Call Simulator States
  const [callActive, setCallActive] = useState(false);
  const [callType, setCallType] = useState<EmergencyType | null>(null);
  const [callDuration, setCallDuration] = useState(0);
  const [callLogs, setCallLogs] = useState<{ sender: 'operator' | 'user'; text: string }[]>([]);
  const [callInput, setCallInput] = useState('');
  const [callStatus, setCallStatus] = useState<'ringing' | 'connected' | 'ended'>('ringing');

  const load = async () => {
    if (!session?.user) return;
    const { data } = await supabase
      .from('emergency_requests')
      .select('*')
      .eq('user_id', session.user.id)
      .order('created_at', { ascending: false })
      .limit(6);
    setRequests(data ?? []);
    setLoading(false);
  };

  useEffect(() => {
    load();
  }, [session]);

  // Continuously track high-precision GPS
  useEffect(() => {
    if ('geolocation' in navigator) {
      const watchId = navigator.geolocation.watchPosition(
        (pos) => {
          setCurrentLat(pos.coords.latitude);
          setCurrentLng(pos.coords.longitude);
          setGpsAccuracy(Math.round(pos.coords.accuracy || 4));
          setTrackingGps(true);
        },
        (err) => console.warn("GPS tracking warning:", err),
        { enableHighAccuracy: true, maximumAge: 5000, timeout: 10000 }
      );
      return () => navigator.geolocation.clearWatch(watchId);
    }
  }, []);

  // Voice Recognition Setup
  useEffect(() => {
    const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if (SpeechRecognition) {
      const recog = new SpeechRecognition();
      recog.continuous = false;
      recog.interimResults = false;
      recog.lang = 'en-IN';

      recog.onresult = (event: any) => {
        const text = event.results[0][0].transcript;
        setSpeechTranscript(text);
        setIsListening(false);
        handleAIVoiceTriage(text);
      };

      recog.onerror = () => setIsListening(false);
      recog.onend = () => setIsListening(false);
      recognitionRef.current = recog;
    }
  }, []);

  // Countdown timer for SOS trigger
  useEffect(() => {
    if (confirmType === null) return;
    setCountdown(3);
    const interval = setInterval(() => {
      setCountdown((c) => {
        if (c <= 1) {
          clearInterval(interval);
          sendSOS(confirmType);
          return 0;
        }
        return c - 1;
      });
    }, 1000);
    return () => clearInterval(interval);
  }, [confirmType]);

  // Call duration timer
  useEffect(() => {
    let interval: any;
    if (callActive && callStatus === 'connected') {
      interval = setInterval(() => {
        setCallDuration((d) => d + 1);
      }, 1000);
    }
    return () => clearInterval(interval);
  }, [callActive, callStatus]);

  // Synthesize speech output
  const speak = (msg: string) => {
    if ('speechSynthesis' in window) {
      window.speechSynthesis.cancel();
      const utterance = new SpeechSynthesisUtterance(msg);
      utterance.rate = 1.05;
      utterance.pitch = 1.0;
      window.speechSynthesis.speak(utterance);
    }
  };

  // Toggle Emergency Siren Generator (AudioContext)
  const toggleSiren = () => {
    if (sirenPlaying) {
      if (oscRef.current) {
        try { oscRef.current.stop(); } catch (e) {}
      }
      setSirenPlaying(false);
    } else {
      try {
        const AudioCtx = window.AudioContext || (window as any).webkitAudioContext;
        const ctx = new AudioCtx();
        const osc = ctx.createOscillator();
        const gain = ctx.createGain();

        osc.type = 'sawtooth';
        osc.frequency.setValueAtTime(800, ctx.currentTime);
        osc.frequency.linearRampToValueAtTime(1300, ctx.currentTime + 0.4);
        osc.frequency.linearRampToValueAtTime(800, ctx.currentTime + 0.8);

        gain.gain.setValueAtTime(0.3, ctx.currentTime);
        osc.connect(gain);
        gain.connect(ctx.destination);
        osc.start();

        audioCtxRef.current = ctx;
        oscRef.current = osc;
        setSirenPlaying(true);
      } catch (e) {
        console.warn("Audio oscillator error:", e);
      }
    }
  };

  // AI Voice Triage Handler
  const handleAIVoiceTriage = (spokenText: string) => {
    const txt = spokenText.toLowerCase();
    let detectedType: EmergencyType = 'ambulance';

    if (txt.includes('police') || txt.includes('thief') || txt.includes('break') || txt.includes('attack') || txt.includes('rob') || txt.includes('stalk') || txt.includes('danger')) {
      detectedType = 'police';
    } else if (txt.includes('fire') || txt.includes('smoke') || txt.includes('burn') || txt.includes('gas') || txt.includes('blast') || txt.includes('spark')) {
      detectedType = 'fire';
    } else if (txt.includes('flood') || txt.includes('cyclone') || txt.includes('collapse') || txt.includes('electric wire') || txt.includes('water logging')) {
      detectedType = 'disaster';
    } else {
      detectedType = 'ambulance';
    }

    sendSOS(detectedType, spokenText);
  };

  const toggleVoiceAssistant = () => {
    if (isListening) {
      recognitionRef.current?.stop();
      setIsListening(false);
    } else {
      if (recognitionRef.current) {
        setIsListening(true);
        recognitionRef.current.start();
        speak("CityZen SOS AI is listening. State your emergency now.");
      } else {
        alert("Speech recognition not supported on this browser. Please use quick dispatch buttons.");
      }
    }
  };

  // Generate Step-by-Step AI Guidance Protocols
  const generateAIProtocols = (type: EmergencyType, details: string = '') => {
    const txt = details.toLowerCase();
    let steps: AIProtocolStep[] = [];
    let severity: 'CRITICAL_L1' | 'HIGH_L2' | 'MODERATE_L3' = 'HIGH_L2';

    if (type === 'ambulance') {
      if (txt.includes('chest') || txt.includes('heart') || txt.includes('cardiac') || txt.includes('unconscious')) {
        severity = 'CRITICAL_L1';
        steps = [
          { title: 'Position Patient', detail: 'Help patient sit comfortably leaning slightly forward, loosen collar and tight belts.', important: true },
          { title: 'Check Responsiveness & Breathing', detail: 'Tap shoulder and ask loudly if they hear you. Check chest movement for 10 seconds.' },
          { title: 'CPR Ready Protocol', detail: 'If unresponsive with no normal breathing, push hard & fast in center of chest (100–120 bpm, ~2 inches deep).' },
          { title: 'Do Not Give Solid Food', detail: 'Keep patient calm, do not administer solid food or water while breathless.' }
        ];
      } else if (txt.includes('bleed') || txt.includes('accident') || txt.includes('fracture') || txt.includes('cut')) {
        severity = 'HIGH_L2';
        steps = [
          { title: 'Apply Direct Pressure', detail: 'Press clean cloth/bandage firmly on bleeding wound without lifting.', important: true },
          { title: 'Elevate Limb', detail: 'If no bone fracture is suspected, elevate the wounded limb above heart level.' },
          { title: 'Immobilize Bone', detail: 'Do not attempt to push broken bone back. Support limb with rolled cloth/splint.' },
          { title: 'Keep Warm', detail: 'Cover victim with jacket to prevent traumatic hypothermia/shock.' }
        ];
      } else {
        severity = 'HIGH_L2';
        steps = [
          { title: 'Ensure Clear Airway', detail: 'Turn patient to side (recovery position) if vomiting or semi-conscious.', important: true },
          { title: 'Keep Ambient Airflow', detail: 'Disperse crowds and ensure fresh cross-ventilation around patient.' },
          { title: 'Gather Medications', detail: 'Have current prescriptions and ID cards ready for the arriving paramedics.' }
        ];
      }
    } else if (type === 'police') {
      if (txt.includes('break') || txt.includes('weapon') || txt.includes('intruder') || txt.includes('attack')) {
        severity = 'CRITICAL_L1';
        steps = [
          { title: 'Lock & Barricade Doors', detail: 'Move into a lockable room immediately. Lock doors, latch windows and pull curtains.', important: true },
          { title: 'Silence All Devices', detail: 'Mute your smartphone ringer and vibration completely to avoid detection.' },
          { title: 'Stay Low Out of Sight', detail: 'Sit on the floor behind heavy furniture away from window sightlines.' },
          { title: 'Keep Live GPS Beacon', detail: 'Do not hang up dispatch. Police patrol unit Delta-4 is zeroing in on your coordinates.' }
        ];
      } else {
        severity = 'HIGH_L2';
        steps = [
          { title: 'Stay in Public View', detail: 'Move towards well-lit streets or populated shops if in open area.', important: true },
          { title: 'Note Suspect Features', detail: 'Mentally note vehicle license number, clothing color, height, and direction taken.' },
          { title: 'Do Not Confront', detail: 'Keep safe distance and wait for uniformed patrol intercept.' }
        ];
      }
    } else if (type === 'fire') {
      severity = 'CRITICAL_L1';
      steps = [
        { title: 'Evacuate Immediately', detail: 'Alert all occupants and exit via nearest staircase. Never use elevators.', important: true },
        { title: 'Crawl Below Smoke', detail: 'Toxic gases rise. Keep your head 1–2 feet above floor where air is cleanest.' },
        { title: 'Test Doorknobs', detail: 'Feel metal doorknobs with back of hand before opening. If hot, use alternate exit.' },
        { title: 'Gas Cylinder Isolation', detail: 'If LPG smell detected, shut main cylinder regulator valve without touching switches.' }
      ];
    } else {
      severity = 'HIGH_L2';
      steps = [
        { title: 'Seek Elevated Ground', detail: 'If flood waters are rising, move to the 2nd floor or higher immediately.', important: true },
        { title: 'Isolate Main Breaker', detail: 'Switch off main electrical circuit board to prevent electrocution hazard.' },
        { title: 'Avoid Submerged Roads', detail: 'Never walk or drive through moving water — 6 inches can sweep vehicles away.' }
      ];
    }

    setTriageSeverity(severity);
    setProtocolSteps(steps);
  };

  const startOperatorCall = (type: EmergencyType, locationName: string, initialTranscript: string = '') => {
    setCallType(type);
    setCallStatus('ringing');
    setCallDuration(0);
    setCallActive(true);
    setCallLogs([]);
    generateAIProtocols(type, initialTranscript);

    speak("Connecting to CityZen Emergency Central Dispatch...");

    setTimeout(() => {
      setCallStatus('connected');
      const welcomeMsg = `Emergency central dispatch online. We have locked your ${type.toUpperCase()} GPS coordinates at ${locationName.split('(')[0].trim()}. Responder unit is alerted. State your current situation.`;
      setCallLogs([{ sender: 'operator', text: welcomeMsg }]);
      speak(welcomeMsg);
    }, 1800);
  };

  const handleOperatorRespond = async (inputText: string) => {
    if (!inputText.trim() || !active) return;
    setCallLogs((prev) => [...prev, { sender: 'user', text: inputText.trim() }]);
    setCallInput('');

    generateAIProtocols(active.type, inputText);

    const newNotes = `Emergency update: "${inputText.trim()}" (Triage: ${triageSeverity})`;
    await supabase.from('emergency_requests').update({ notes: newNotes }).eq('id', active.id);

    let reply = "";
    const txt = inputText.toLowerCase();

    if (active.type === 'police') {
      if (txt.includes('break-in') || txt.includes('robbery') || txt.includes('theft') || txt.includes('intruder')) {
        reply = "Active threat confirmed. PCR Patrol Delta-4 is 3 minutes away with beacon active. Barricade yourself immediately.";
      } else if (txt.includes('accident') || txt.includes('crash')) {
        reply = "Traffic collision logged. Highway patrol and ambulance unit routed. Keep clear of oncoming lanes.";
      } else {
        reply = "Police unit is approaching your GPS coordinates. Stay in a safe perimeter.";
      }
    } else if (active.type === 'ambulance') {
      if (txt.includes('chest') || txt.includes('heart') || txt.includes('pain') || txt.includes('cardiac')) {
        reply = "Cardiac emergency protocol active. Advanced Life Support ambulance en route (ETA 4 min). Loosen clothing and follow CPR guide.";
      } else if (txt.includes('breath') || txt.includes('chok')) {
        reply = "Respiratory distress logged. Paramedics dispatched with oxygen support. Keep patient seated upright.";
      } else {
        reply = "Ambulance dispatched. Medical team will home in on your live GPS beacon.";
      }
    } else if (active.type === 'fire') {
      if (txt.includes('gas') || txt.includes('leak') || txt.includes('lpg')) {
        reply = "Hazardous gas leak logged. Fire tender Echo-3 responding. Turn off regulator, do not operate switches, evacuate now.";
      } else {
        reply = "Structural fire logged. Fire rescue dispatched. Evacuate immediately and assemble at designated safe zone.";
      }
    } else {
      if (txt.includes('flood') || txt.includes('water')) {
        reply = "Flash flood response alert en route with inflatable rescue boats. Climb to upper levels immediately.";
      } else {
        reply = "Disaster rescue squad active and tracking your beacon. Stay sheltered.";
      }
    }

    setTimeout(() => {
      setCallLogs((prev) => [...prev, { sender: 'operator', text: reply }]);
      speak(reply);
    }, 700);
  };

  const endCall = () => {
    if ('speechSynthesis' in window) window.speechSynthesis.cancel();
    setCallActive(false);
    setCallStatus('ended');
  };

  const sendSOS = async (type: EmergencyType, spokenQuery: string = '') => {
    if (!session?.user) return;

    let locationText = `Lat: ${currentLat.toFixed(4)}, Lng: ${currentLng.toFixed(4)} (Bhubaneswar, Odisha)`;

    try {
      const { data: points } = await supabase.from('map_points').select('name, lat, lng');
      let nearestLandmark = '';
      let minDistance = Infinity;
      
      if (points && points.length > 0) {
        for (const p of points) {
          const dist = getDistance(currentLat, currentLng, Number(p.lat), Number(p.lng));
          if (dist < minDistance) {
            minDistance = dist;
            nearestLandmark = p.name;
          }
        }
      }

      if (nearestLandmark && minDistance < 5) {
        locationText = `Near ${nearestLandmark} (Lat: ${currentLat.toFixed(4)}, Lng: ${currentLng.toFixed(4)}, Accuracy ±${gpsAccuracy}m)`;
      }
    } catch (e) {
      console.warn("Landmark lookup error:", e);
    }

    const initialNotes = spokenQuery 
      ? `Voice SOS: "${spokenQuery}"` 
      : 'Emergency SOS dispatched via one-tap beacon';

    const { data } = await supabase.from('emergency_requests').insert({
      user_id: session.user.id,
      type,
      location_text: locationText,
      lat: currentLat,
      lng: currentLng,
      notes: initialNotes,
    }).select('*').single();

    await supabase.from('notifications').insert({
      user_id: session.user.id,
      title: `${type.toUpperCase()} Emergency Dispatched`,
      message: `Emergency services dispatched to your coordinates. Help is en route.`,
      type: 'emergency',
    });

    setConfirmType(null);
    if (data) {
      setActive(data as EmergencyRequest);
      startOperatorCall(type, locationText, spokenQuery);
    }
    load();
  };

  const cancelSOS = () => {
    setConfirmType(null);
  };

  const resolveActive = async () => {
    if (!active) return;
    await supabase.from('emergency_requests').update({ status: 'resolved', resolved_at: new Date().toISOString() }).eq('id', active.id);
    setActive(null);
    if (sirenPlaying) toggleSiren();
    load();
  };

  return (
    <Screen>
      <ScreenHeader title="Emergency SOS" subtitle="AI Auto-Triage & Live Beacon" onBack={onBack} />

      {/* Main Top Banner with AI Voice & Siren Options */}
      <div className="px-4 py-4 space-y-3">
        <div className="bg-gradient-to-br from-error-600 via-error-500 to-rose-700 rounded-3xl p-5 text-white shadow-xl shadow-error-500/20 relative overflow-hidden">
          <div className="relative z-10 space-y-3">
            <div className="flex items-center justify-between">
              <span className="px-2.5 py-1 bg-white/20 backdrop-blur-md rounded-full text-[10px] font-extrabold uppercase tracking-wider flex items-center gap-1.5">
                <Radio className="w-3 h-3 animate-pulse text-amber-300" /> Live AI Telemetry Active
              </span>
              <button
                onClick={toggleSiren}
                className={`px-3 py-1 rounded-full text-[10px] font-bold flex items-center gap-1.5 transition-all cursor-pointer ${
                  sirenPlaying ? 'bg-white text-error-600 animate-bounce' : 'bg-black/30 hover:bg-black/50 text-white'
                }`}
              >
                {sirenPlaying ? <Volume2 className="w-3.5 h-3.5" /> : <VolumeX className="w-3.5 h-3.5" />}
                {sirenPlaying ? 'Siren Alarm ON' : 'Trigger Siren'}
              </button>
            </div>

            <div>
              <p className="text-xl font-black tracking-tight">Instant SOS Dispatch</p>
              <p className="text-white/80 text-xs mt-0.5">High-precision GPS coordinates locked to closest responder grid.</p>
            </div>

            {/* Voice SOS AI Trigger Bar */}
            <div className="pt-1">
              <button
                onClick={toggleVoiceAssistant}
                className={`w-full py-3 px-4 rounded-2xl flex items-center justify-between text-xs font-bold transition-all shadow-md cursor-pointer ${
                  isListening 
                    ? 'bg-amber-400 text-slate-950 animate-pulse ring-2 ring-white' 
                    : 'bg-white text-error-700 hover:bg-rose-50'
                }`}
              >
                <div className="flex items-center gap-2">
                  <div className={`w-7 h-7 rounded-full flex items-center justify-center ${isListening ? 'bg-black text-amber-300' : 'bg-error-100 text-error-600'}`}>
                    {isListening ? <Mic className="w-4 h-4 animate-bounce" /> : <Sparkles className="w-4 h-4" />}
                  </div>
                  <span>{isListening ? 'Listening to voice... speak now!' : 'Speak with SOS AI Auto-Triage'}</span>
                </div>
                <span className="text-[10px] font-extrabold uppercase px-2 py-0.5 bg-error-600/10 rounded-md">
                  {isListening ? 'Active' : 'AI Voice'}
                </span>
              </button>
              {speechTranscript && (
                <p className="text-[11px] text-amber-200 mt-1.5 italic truncate font-mono">"{speechTranscript}"</p>
              )}
            </div>

            {/* GPS Telemetry Bar */}
            <div className="flex items-center justify-between text-[11px] bg-black/25 backdrop-blur-md px-3 py-1.5 rounded-xl border border-white/10">
              <span className="flex items-center gap-1 text-white/90">
                <LocateFixed className="w-3.5 h-3.5 text-emerald-400" />
                GPS: {currentLat.toFixed(4)}, {currentLng.toFixed(4)}
              </span>
              <span className="font-mono text-[10px] text-emerald-300 font-bold">±{gpsAccuracy}m Accuracy</span>
            </div>
          </div>
        </div>

        {/* Emergency Type Grid */}
        <div className="grid grid-cols-2 gap-3">
          {types.map(({ value, label, icon: Icon, color, bg, phone, desc }) => (
            <button
              key={value}
              onClick={() => setConfirmType(value)}
              className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl p-4 flex flex-col justify-between text-left shadow-sm hover:shadow-md transition-all group cursor-pointer"
            >
              <div className="flex items-center justify-between mb-3">
                <div className={`w-12 h-12 rounded-2xl ${bg} flex items-center justify-center group-hover:scale-105 transition-transform text-white shadow-md`}>
                  <Icon className="w-6 h-6" />
                </div>
                <span className="text-[11px] font-black font-mono px-2 py-0.5 bg-ink-100 dark:bg-slate-800 text-ink-700 dark:text-slate-300 rounded-lg">
                  {phone}
                </span>
              </div>
              <div>
                <p className="font-bold text-ink-900 dark:text-white text-sm">{label}</p>
                <p className="text-[10px] text-ink-400 dark:text-slate-400 mt-0.5 line-clamp-1">{desc}</p>
              </div>
            </button>
          ))}
        </div>
      </div>

      {/* Active emergency banner & AI Protocol First Responder Guidance */}
      {active && (
        <div className="px-4 pb-4 space-y-3">
          <div className="bg-error-500/10 border-2 border-error-500/30 rounded-3xl p-4 animate-fade-in space-y-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2 text-error-600">
                <div className="relative w-3 h-3">
                  <div className="absolute inset-0 rounded-full bg-error-500 pulse-ring" />
                  <div className="absolute inset-0 rounded-full bg-error-500" />
                </div>
                <p className="font-black text-sm">SOS DISPATCH ACTIVE · {active.type.toUpperCase()}</p>
              </div>
              <span className={`px-2 py-0.5 rounded-full text-[9px] font-extrabold uppercase ${
                triageSeverity === 'CRITICAL_L1' ? 'bg-red-600 text-white animate-pulse' : 'bg-amber-500 text-white'
              }`}>
                {triageSeverity.replace('_', ' ')}
              </span>
            </div>

            <p className="text-xs text-ink-600 dark:text-slate-300">
              Emergency responders have received your beacon and exact coordinates. Live guidance generated below:
            </p>

            {/* AI Protocol Steps */}
            {protocolSteps.length > 0 && (
              <div className="bg-white/80 dark:bg-slate-900/80 rounded-2xl p-3.5 border border-error-500/20 space-y-2">
                <div className="flex items-center gap-1.5 text-xs font-bold text-error-700 dark:text-error-400 uppercase tracking-wider">
                  <LifeBuoy className="w-4 h-4" /> AI First-Aid Action Protocol
                </div>
                <div className="space-y-2">
                  {protocolSteps.map((step, idx) => (
                    <div key={idx} className="flex gap-2 items-start text-xs">
                      <span className={`w-4 h-4 rounded-full flex items-center justify-center text-[9px] font-bold shrink-0 mt-0.5 ${
                        step.important ? 'bg-error-600 text-white font-black' : 'bg-ink-200 dark:bg-slate-800 text-ink-700 dark:text-slate-300'
                      }`}>
                        {idx + 1}
                      </span>
                      <div>
                        <span className="font-bold text-ink-900 dark:text-white block">{step.title}</span>
                        <span className="text-ink-500 dark:text-slate-400 text-[11px] leading-tight">{step.detail}</span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            <div className="flex gap-2 pt-1">
              <Button variant="danger" size="sm" onClick={resolveActive} className="flex-1">
                <CheckCircle2 className="w-4 h-4" /> Mark Emergency Resolved
              </Button>
              <button
                onClick={() => setCallActive(true)}
                className="px-4 py-2 bg-primary-600 hover:bg-primary-700 text-white rounded-xl text-xs font-bold flex items-center gap-1.5 cursor-pointer shadow-sm"
              >
                <Radio className="w-3.5 h-3.5" /> Re-open Dispatcher
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Recent emergencies list */}
      <div className="px-4 pb-6">
        <h2 className="font-bold text-ink-900 dark:text-white text-sm mb-3">Recent SOS Dispatches</h2>
        {loading ? (
          <div className="space-y-2">
            {[1, 2].map((i) => <div key={i} className="bg-white dark:bg-slate-900 rounded-2xl h-16 skeleton" />)}
          </div>
        ) : requests.length === 0 ? (
          <div className="bg-white dark:bg-slate-900 rounded-2xl p-6 text-center text-sm text-ink-400 dark:text-slate-400 border border-slate-100 dark:border-slate-800">
            No emergency requests logged. Stay safe!
          </div>
        ) : (
          <div className="space-y-2.5">
            {requests.map((r) => {
              const cfg = types.find((t) => t.value === r.type) || types[0];
              return (
                <div key={r.id} className="bg-white dark:bg-slate-900 rounded-2xl p-4 flex items-center gap-3 shadow-sm border border-slate-100 dark:border-slate-800">
                  <div className={`w-10 h-10 rounded-xl ${cfg.bg} flex items-center justify-center shrink-0 shadow-sm`}>
                    <cfg.icon className="w-5 h-5 text-white" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="font-semibold text-ink-800 dark:text-white capitalize text-sm">{r.type}</p>
                    <p className="text-xs text-ink-400 dark:text-slate-400 flex items-center gap-1 truncate">
                      <MapPin className="w-3 h-3 text-primary-600 shrink-0" /> {r.location_text} · {timeAgo(r.created_at)}
                    </p>
                  </div>
                  <span className={`text-[10px] font-semibold px-2 py-1 rounded-full capitalize shrink-0 ${
                    r.status === 'active' ? 'bg-error-500/10 text-error-600' :
                    r.status === 'dispatched' ? 'bg-accent-500/10 text-accent-600' :
                    'bg-emerald-100 text-emerald-700'
                  }`}>
                    {r.status}
                  </span>
                </div>
              );
            })}
          </div>
        )}
      </div>

      {/* Confirm modal */}
      <Modal open={confirmType !== null} onClose={cancelSOS} title="Confirm SOS Dispatch">
        {confirmType && (
          <div className="text-center space-y-5">
            <div className="relative w-24 h-24 mx-auto">
              <div className="absolute inset-0 rounded-full bg-error-500/20 animate-ping" />
              <div className="absolute inset-2 rounded-full bg-error-500 flex items-center justify-center">
                <AlertTriangle className="w-10 h-10 text-white" />
              </div>
            </div>
            <div>
              <p className="text-lg font-bold text-ink-900">Send {confirmType.toUpperCase()} SOS?</p>
              <p className="text-xs text-ink-500 mt-1">Your exact GPS coordinates ({currentLat.toFixed(4)}, {currentLng.toFixed(4)}) and caller details will be broadcast to emergency services.</p>
            </div>
            <div className="bg-error-500/10 rounded-xl p-3">
              <p className="text-error-600 font-bold text-2xl">{countdown}</p>
              <p className="text-xs text-ink-500">Auto-dispatching in {countdown} second{countdown !== 1 ? 's' : ''}…</p>
            </div>
            <Button variant="outline" size="lg" className="w-full" onClick={cancelSOS}>
              <X className="w-4 h-4" /> Cancel Dispatch
            </Button>
          </div>
        )}
      </Modal>

      {/* Call Simulator Overlay */}
      {callActive && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-ink-950/85 backdrop-blur-md p-4">
          <div className="bg-slate-900 border border-white/10 w-full max-w-md rounded-3xl p-5 flex flex-col h-[80vh] justify-between shadow-2xl animate-scale-in text-white">
            {/* Call Header */}
            <div className="text-center space-y-2 border-b border-white/10 pb-3">
              <div className="relative w-14 h-14 mx-auto mb-1">
                <div className="absolute inset-0 rounded-full bg-error-500/20 animate-ping" />
                <div className="absolute inset-2 rounded-full bg-error-500 flex items-center justify-center">
                  <Phone className="w-5 h-5 text-white" />
                </div>
              </div>
              <h3 className="font-black text-white text-base tracking-wide">CITYZEN CENTRAL DISPATCH</h3>
              <p className="text-[11px] text-error-400 font-bold uppercase tracking-widest flex items-center justify-center gap-1.5">
                <span className="w-2 h-2 rounded-full bg-error-500 animate-ping" />
                {callStatus === 'ringing' ? 'Establishing Encrypted Channel...' : `Connected (${Math.floor(callDuration / 60)}:${String(callDuration % 60).padStart(2, '0')})`}
              </p>
              <p className="text-[11px] text-ink-300 font-medium px-4 truncate">
                {active?.location_text || 'Bhubaneswar, Odisha'}
              </p>
            </div>

            {/* Conversation Log */}
            <div className="flex-1 overflow-y-auto my-3 space-y-3 px-2 py-3 bg-black/30 rounded-2xl border border-white/5">
              {callLogs.map((log, i) => (
                <div key={i} className={`flex ${log.sender === 'user' ? 'justify-end' : 'justify-start'}`}>
                  <div className={`max-w-[85%] px-3.5 py-2.5 rounded-2xl text-xs leading-relaxed ${
                    log.sender === 'user' 
                      ? 'bg-primary-600 text-white rounded-tr-sm shadow-md' 
                      : 'bg-slate-800 text-slate-100 border border-white/10 rounded-tl-sm shadow-md'
                  }`}>
                    {log.text}
                  </div>
                </div>
              ))}
              {callStatus === 'ringing' && (
                <p className="text-center text-xs text-ink-400 animate-pulse mt-12">Pinging emergency cell tower...</p>
              )}
            </div>

            {/* Quick Actions & Input row */}
            <div className="space-y-3 shrink-0">
              {callStatus === 'connected' && (
                <div className="space-y-1.5">
                  <p className="text-[9px] font-extrabold text-slate-400 tracking-wider uppercase">Quick Incident Cues</p>
                  <div className="grid grid-cols-2 gap-1.5">
                    {callType === 'police' && ['Active break-in', 'Assault/Threat', 'Traffic Accident', 'Intruder spotted'].map(t => (
                      <button key={t} onClick={() => handleOperatorRespond(t)} className="px-2.5 py-1.5 bg-slate-800 hover:bg-slate-700 text-white text-[10px] rounded-xl text-left truncate font-semibold border border-white/5 cursor-pointer">
                        {t}
                      </button>
                    ))}
                    {callType === 'ambulance' && ['Chest pain/Heart', 'Breathing distress', 'Severe Bleeding', 'Unconscious casualty'].map(t => (
                      <button key={t} onClick={() => handleOperatorRespond(t)} className="px-2.5 py-1.5 bg-slate-800 hover:bg-slate-700 text-white text-[10px] rounded-xl text-left truncate font-semibold border border-white/5 cursor-pointer">
                        {t}
                      </button>
                    ))}
                    {callType === 'fire' && ['Building fire', 'Electrical spark', 'LPG Gas leak', 'Trapped in smoke'].map(t => (
                      <button key={t} onClick={() => handleOperatorRespond(t)} className="px-2.5 py-1.5 bg-slate-800 hover:bg-slate-700 text-white text-[10px] rounded-xl text-left truncate font-semibold border border-white/5 cursor-pointer">
                        {t}
                      </button>
                    ))}
                    {callType === 'disaster' && ['Rising flood water', 'Live high-tension wire', 'Structure collapse', 'Road landslide'].map(t => (
                      <button key={t} onClick={() => handleOperatorRespond(t)} className="px-2.5 py-1.5 bg-slate-800 hover:bg-slate-700 text-white text-[10px] rounded-xl text-left truncate font-semibold border border-white/5 cursor-pointer">
                        {t}
                      </button>
                    ))}
                  </div>
                </div>
              )}

              {/* TextInput / End Call row */}
              <div className="flex gap-2">
                <input
                  type="text"
                  placeholder={callStatus === 'connected' ? "Speak or type updates..." : "Connecting..."}
                  disabled={callStatus !== 'connected'}
                  value={callInput}
                  onChange={(e) => setCallInput(e.target.value)}
                  onKeyDown={(e) => e.key === 'Enter' && handleOperatorRespond(callInput)}
                  className="flex-1 px-3.5 py-2.5 text-xs bg-black/40 border border-white/10 text-white rounded-xl focus:outline-none focus:border-primary-500 placeholder:text-slate-500"
                />
                <button
                  disabled={callStatus !== 'connected' || !callInput.trim()}
                  onClick={() => { if (callInput.trim()) handleOperatorRespond(callInput); }}
                  className="px-4 bg-primary-600 hover:bg-primary-700 disabled:opacity-40 text-white rounded-xl text-xs font-bold cursor-pointer transition-colors"
                >
                  Send
                </button>
              </div>

              <Button variant="danger" size="sm" className="w-full flex items-center justify-center gap-2" onClick={endCall}>
                <X className="w-4 h-4" /> Disconnect Call
              </Button>
            </div>
          </div>
        </div>
      )}
    </Screen>
  );
}
